[project]
name = "minesweeper3d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ursina>=7.0.0",
    "z3-solver>=4.14.1.0",
]
